name: HTML CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tidy (HTML validator)
      run: sudo apt-get install tidy

    - name: Validate HTML files
      run: |
        find . -name "*.html" -exec tidy -q -e {} \;
